# [START cloudbuild_basic_config]
steps:
  - name: gradle:7.5-jdk11
    entrypoint: gradle
    args: [ 'assemble' ]

  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t',
            'gcr.io/animated-bonsai-331019/myimage',
            '.' ]

  # Docker Push
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push',
            'gcr.io/animated-bonsai-331019/myimage' ]

  #Login GCLOUD
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: [ 'auth', 'activate-service-account', '304952370723-compute@developer.gserviceaccount.com',
            '--key-file=me.json' ]


  # Entrypoint, timeout and environment variables
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: [ 'compute', 'instances',
            'update', 'my-vm-name',
            '--container-image',
            'gcr.io/animated-bonsai-331019/myimage'
    ]
    env:
      - 'CLOUDSDK_COMPUTE_REGION=us-east1'
      - 'CLOUDSDK_COMPUTE_ZONE=us-east1-c'
# [END cloudbuild_basic_config]